version: '3.4'

volumes:
  demo1-data:
    name: demo1-data
    external: true
  demo1-pgadmin-data:
    name: demo1-pgadmin-data
    external: true

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    volumes:
      - demo1-pgadmin-data:/var/lib/pgadmin
    env_file:
      - .\config\var_pgadmin_config.txt
    ports:
      - 8088:80
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile
    image: yrosman/postgres12.3-postgis2.5
    container_name: postgres12-postgis2.5
    restart: always
    volumes:
      - demo1-data:/var/lib/postgresql/data/
    env_file:
      - .\config\var_postgres_config.txt
    ports:
      - 5432:5432
